### PR TITLE
Fix TextInput placeholder issues

### PR DESCRIPTION
**Pull request by Dremora**
Fixes the following issues:
1) Having placeholder makes it impossible to activate input due to pointer-events not being accepted by Text
2) TextInput placeholder doesn't match up with text (#119)

I have originally only tried to fix (1), but then discovered issue #119 where @tuckerconnelly has already provided a working solution — so all credits really goes to him :)

### CODE REVIEW

**Comment by MoOx** [comment]
Tests are failing on Firefox https://travis-ci.org/necolas/react-native-web/jobs/128455292#L1670

**Comment by Dremora** [comment]
I'll have a look at it tonight!

**Comment by jsierles** [comment]
Any update on this?

**Comment by jsierles** [comment]
This fixes the tests, just need to check one level down the component hierarchy: https://github.com/jsierles/react-native-web/commit/d2666d2694f0c555f35f749e5b8540ff317285ba

**Comment by Dremora** [comment]
Sorry, didn't have much time to look at this. Thanks for the tests, I've added them to this PR (still credited to you).

**Comment by bmcmahen** [comment]
Any progress on this? Would you accept a new PR for this @necolas ?

**Pull request closed without merging**
