### PR TITLE
[fix] cannot convert undefined or null to object if node already unmo…

### PR DESCRIPTION
**Pull request by johakr**
…unted in resizeObserver

### CODE REVIEW

**Comment by necolas** [comment]
Have you got example code of the issue this is meant to fix?

**Comment by johakr** [comment]
I will try to cutout an example repository, but this will take some time (probably weeks) since the project this issue occurs in is quite complex. The specific place where this issue occurs is when I use Flipkart/recyclerlistview and add new elements to the top of the list. I don't know if that's an issue with recyclelistview in the first place, but I think react-native-web should be robust enough to handle those kind of edge cases.

**Comment by necolas** [comment]
> The specific place where this issue occurs is when I use Flipkart/recyclerlistview and add new elements to the top of the list

Is that something that can be reproduced with a reduced test case in codesandbox? Test cases are probably the most important thing when making changes. It gives everyone an example that can be used to check for regressions and understand where in the code issues originate from. Right now I can't see how calling `observe` in those lifestyle methods could happen while the component is unmounted, so I just want to understand what is going on. Thanks

**Comment by necolas** [comment]
Did you make a test case yet?

**Comment by johakr** [comment]
Sorry, really tried to come up with a reduced test case to reproduce this issue, but had no luck and really am out of ideas. Must be some kind of obscure race condition. Since we moved to another implementation in our main project, there is no pressure from my side to get this merged. So feel free to close this pull request, if you see no need to get this merged.

For what it's worth here's the error call stack:

`Uncaught TypeError: Cannot convert undefined or null to object
    at unobserve (index.js?20e4:67)
    at Text.componentWillUnmount (index.js?20e4:107)
    at callComponentWillUnmountWithTimer (react-dom.development.js?61bb:9703)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:138)
    at invokeGuardedCallback (react-dom.development.js?61bb:187)
    at safelyCallComponentWillUnmount (react-dom.development.js?61bb:9710)
    at commitUnmount (react-dom.development.js?61bb:9956)
    at unmountHostComponents (react-dom.development.js?61bb:10299)
    at commitDeletion (react-dom.development.js?61bb:10329)`

**Comment by necolas** [comment]
Another implementation of what?

**Comment by johakr** [comment]
We dropped `Flipkart/recyclerlistview`

**Comment by necolas** [comment]
Out of interest, what are you using instead?

**Pull request closed without merging**
