### PR TITLE
performance - glamor optimization

### PR DESCRIPTION
**Pull request by threepointone**
very small change. it spreads input styles to `css()`, improves glamor's numbers by ~20%

### CODE REVIEW

**Comment by threepointone** [comment]
added another fix, shaving an additional 20-30% off glamor's numbers.

**Comment by threepointone** [comment]
before - 
```
performance.bundle.js:36 Deep tree [glamor]
178.19ms ±10.84ms
performance.bundle.js:36 Wide tree [glamor]
311.17ms ±13.76ms
```

after -
```
performance.bundle.js:36 Deep tree [glamor]
83.67ms ±11.46ms
performance.bundle.js:36 Wide tree [glamor]
164.42ms ±9.98ms
```

**Comment by necolas** [comment]
Thanks! I figured I'd done something wrong as there's no way glamor should be almost as slow as styled-components

**Comment by necolas** [comment]
Applied in https://github.com/necolas/react-native-web/commit/aa85876eb20b56cc086780499b52d737586c43e4

**Comment by threepointone** [comment]
thanks much! it should also get a touch faster with the next release of glamor; with that I'm currently getting ~10ms diff with rnw on deep tree, and ~20-25ms on the wide tree. 

thanks for pushing me to do this!

**Comment by necolas** [comment]
That's great!

**Pull request closed without merging**
