### PR TITLE
Added support for directly requiring image assets (rebase, +docs & tests)

### PR DESCRIPTION
**Pull request by IjzerenHein**
Native-script allows for directly requiring image assets without the need of wrapping it in an uri object{uri: 'someasset'}. This commit adds this feature <Image source={require('someasset.png')} /> as well as adds strong typing for uri-based sources:

```js
const ImageSourcePropType = PropTypes.oneOfType([
  PropTypes.shape({
    uri: PropTypes.string.isRequired
  }),
  PropTypes.string // Opaque type returned by require('./image.jpg')
])
```
final result, these both work:

```
<Image source={require('../assets/myasset.png')} />
<Image source={{uri: require('../assets/myasset.png')}} />
```

### CODE REVIEW

**Comment by necolas** [comment]
Please can you squash merge this (no need for a new PR, you can update this one)

**Comment by IjzerenHein** [comment]
Sure, no problem if I know how to. How do I squash merge and update this PR?

**Comment by necolas** [comment]
Don't worry, I'll do it as I'm making a couple of small changes.

To squash all commits in a branch I usually make a new branch and do `git merge --squash <original-branch-name>`, check the diff, then write a new commit. Alternatively, interactive `git rebase` which is more flexible (worth googling for some tutorials to familiarize yourself with – you can make clone a branch and play around with interactive rebasing without worry :))

**Comment by IjzerenHein** [comment]
Alright awesome! And thanks for explaining that. I'll make sure to submit consecutive pull requests in proper merged fashion. :) (and without any rebases)

**Comment by necolas** [comment]
It's about a little less noise in the commit history of a patch. I use `git rebase` all the time on my own branches and when merging PRs :).

**Comment by necolas** [comment]
Applied in 6d7d98c149e33e58e941f968697ca44d1e4c1b3a

**Pull request closed without merging**
