### PR TITLE
Add missing lint:cmd

### PR DESCRIPTION
**Pull request by MoOx**
lint:cmd is used in lint-staged config. No failure if everything is already up to date, only happen when you made change that is updated by prettier.

### CODE REVIEW

**Comment by MoOx** [comment]
Not sure why this is failing on jest :/

**Comment by necolas** [comment]
It just timed out. I've noticed that happen a couple of times

**Comment by necolas** [comment]
What I'll do is remove `lint:cmd` and use `eslint` in your other patch adding husky.

**Comment by MoOx** [comment]
lgtm :)

**Pull request closed without merging**
