### PR TITLE
add Image.resolveAssetSource api

### PR DESCRIPTION
**Pull request by dyw934854565**

### CODE REVIEW

**Comment by mosch** [comment]
That looks like an important change resolving this: https://github.com/necolas/react-native-web/issues/1666

**Comment by Younext19** [comment]
could you update please ?

**Comment by dyw934854565** [comment]
> could you update please ?

updated

**Comment by evelant** [comment]
Any reason this can't be merged? I need resolveAssetSource in my app. Seems to be the only thing missing in my initial testing of getting it to run on web.

**Comment by evelant** [comment]
@dyw934854565 why close this? AFAICT it's still useful and needed.

**Pull request closed without merging**
