### PR TITLE
RFC: use Jest

### PR DESCRIPTION
**Pull request by paularmstrong**
**This patch solves the following problem**

Discussed with @necolas about using Jest. Thought I'd see how far I could get using jscodeshift and [these codemod scripts](https://gist.github.com/paularmstrong/30d5304ad36e5844af111f0e5bb487dc). Made no manual changes.

**Problems**

* A lot of tests depend on a real browser environment
* jsdom does not report anything but `0`s for `getBoundingClientRect` (known, will not be fixed)
* Some tests require a network connection to load resources from the Internet

**Test plan**

```
npm run test
npm run test:watch
```

**This pull request**

- [ ] includes documentation
- [x] includes tests
- [ ] includes an interactive example
- [ ] includes screenshots/videos

**Failure Output**

```
> react-native-web@0.0.47 test /Users/paularms/dev/react-native-web
> jest

 FAIL  src/apis/UIManager/__tests__/index-test.js
  ● apis/UIManager › measure › provides correct layout to callback

    expect(received).toEqual(expected)

    Expected value to equal:
      100
    Received:
      0

      at src/apis/UIManager/__tests__/index-test.js:32:11
      at _measureLayout (src/apis/UIManager/index.js:10:1)
      at Object.measure (src/apis/UIManager/index.js:23:1)
      at Object.<anonymous> (src/apis/UIManager/__tests__/index-test.js:31:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at handleMessage (internal/child_process.js:695:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

  ● apis/UIManager › measureLayout › provides correct layout to onSuccess callback

    expect(received).toEqual(expected)

    Expected value to equal:
      40
    Received:
      0

      at src/apis/UIManager/__tests__/index-test.js:65:11
      at _measureLayout (src/apis/UIManager/index.js:10:1)
      at Object.measureLayout (src/apis/UIManager/index.js:33:1)
      at Object.<anonymous> (src/apis/UIManager/__tests__/index-test.js:64:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at handleMessage (internal/child_process.js:695:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

  ● apis/UIManager › measureInWindow › provides correct layout to callback

    expect(received).toEqual(expected)

    Expected value to equal:
      40
    Received:
      0

      at src/apis/UIManager/__tests__/index-test.js:85:11
      at Object.measureInWindow (src/apis/UIManager/index.js:28:1)
      at Object.<anonymous> (src/apis/UIManager/__tests__/index-test.js:84:12)

 FAIL  src/components/Image/__tests__/index-test.js
  ● components/Image › prop "onError"

    TypeError: this.timeout is not a function

      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:50:6)

  ● components/Image › prop "onLoad"

    TypeError: this.timeout is not a function

      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:59:6)

  ● components/Image › prop "onLoadEnd"

    TypeError: this.timeout is not a function

      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:70:6)

  ● components/Image › prop "onLoadStart"

    TypeError: this.timeout is not a function

      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:81:6)

  ● components/Image › prop "source" › encountered a declaration exception

    TypeError: this.timeout is not a function

      at Suite.<anonymous> (src/components/Image/__tests__/index-test.js:119:6)
      at Suite.<anonymous> (src/components/Image/__tests__/index-test.js:118:1)
      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:8:1)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at handleMessage (internal/child_process.js:695:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

 FAIL  src/components/TextInput/__tests__/index-test.js
  ● components/TextInput › prop "maxLength"

    expect(received).toEqual(expected)

    Expected value to equal:
      "10"
    Received:
      10

    Difference:

    Comparing two different types of values:
      Expected: string
      Received: number

      at Object.<anonymous> (src/components/TextInput/__tests__/index-test.js:92:33)

 FAIL  src/modules/createDOMElement/__tests__/index-test.js
  ● modules/createDOMElement › prop "testID"

    expect(received).toEqual(expected)

    Expected value to equal:
      null
    Received:
      undefined

    Difference:

    Comparing two different types of values:
      Expected: null
      Received: undefined

      at Object.<anonymous> (src/modules/createDOMElement/__tests__/index-test.js:53:37)

 PASS  src/components/View/__tests__/index-test.js
  ● Console

    console.error node_modules/fbjs/lib/warning.js:36
      Warning: There is an internal error in the React performance measurement code. Did not expect ctor timer to start while componentDidMount timer is still in progress for another instance.

 PASS  src/components/ProgressBar/__tests__/index-test.js
 PASS  src/components/Text/__tests__/index-test.js
  ● Console

    console.error node_modules/fbjs/lib/warning.js:36
      Warning: There is an internal error in the React performance measurement code. Did not expect ctor timer to start while componentDidMount timer is still in progress for another instance.

 PASS  src/components/Switch/__tests__/index-test.js
 PASS  src/apis/AppRegistry/__tests__/renderApplication-test.js
 PASS  src/apis/AppState/__tests__/index-test.js
 PASS  src/apis/StyleSheet/__tests__/index-test.js
 PASS  src/apis/StyleSheet/__tests__/i18nStyle-test.js
 PASS  src/apis/I18nManager/__tests__/index-test.js
 PASS  src/apis/StyleSheet/__tests__/expandStyle-test.js
 PASS  src/modules/multiplyStyleLengthValue/__tests__/index-test.js
 PASS  src/modules/flattenStyle/__tests__/index-test.js
 PASS  src/apis/StyleSheet/__tests__/processTransform-test.js
 PASS  src/apis/StyleSheet/__tests__/createReactStyleObject-test.js
 PASS  src/apis/StyleSheet/__tests__/normalizeValue-test.js
 PASS  src/apis/StyleSheet/__tests__/processVendorPrefixes-test.js
 PASS  src/apis/StyleSheet/__tests__/processTextShadow-test.js
 FAIL  src/apis/AppRegistry/__tests__/index-test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/jest-cli/build/TestRunner.js:189:18)
      at process._tickCallback (node.js:369:9)

 FAIL  src/apis/AsyncStorage/__tests__/index-test.js (5.124s)
  ● Console

    console.error node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:117
      Unhandled promise rejection [Error: expect(received).toEqual(expected)

      Expected value to equal:
        null
      Received:
        [TypeError: Cannot read property 'setItem' of undefined]

      Difference:

      Comparing two different types of values:
        Expected: null
        Received: object]

  ● apis/AsyncStorage › mergeLocalStorageItem › should have same behavior as react-native

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:477:19)
      at Timer.listOnTimeout (timers.js:92:15)

Summary of all failing tests
 FAIL  src/apis/UIManager/__tests__/index-test.js
  ● apis/UIManager › measure › provides correct layout to callback

    expect(received).toEqual(expected)

    Expected value to equal:
      100
    Received:
      0

      at src/apis/UIManager/__tests__/index-test.js:32:11
      at _measureLayout (src/apis/UIManager/index.js:10:1)
      at Object.measure (src/apis/UIManager/index.js:23:1)
      at Object.<anonymous> (src/apis/UIManager/__tests__/index-test.js:31:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at handleMessage (internal/child_process.js:695:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

  ● apis/UIManager › measureLayout › provides correct layout to onSuccess callback

    expect(received).toEqual(expected)

    Expected value to equal:
      40
    Received:
      0

      at src/apis/UIManager/__tests__/index-test.js:65:11
      at _measureLayout (src/apis/UIManager/index.js:10:1)
      at Object.measureLayout (src/apis/UIManager/index.js:33:1)
      at Object.<anonymous> (src/apis/UIManager/__tests__/index-test.js:64:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at handleMessage (internal/child_process.js:695:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

  ● apis/UIManager › measureInWindow › provides correct layout to callback

    expect(received).toEqual(expected)

    Expected value to equal:
      40
    Received:
      0

      at src/apis/UIManager/__tests__/index-test.js:85:11
      at Object.measureInWindow (src/apis/UIManager/index.js:28:1)
      at Object.<anonymous> (src/apis/UIManager/__tests__/index-test.js:84:12)

 FAIL  src/components/Image/__tests__/index-test.js
  ● components/Image › prop "onError"

    TypeError: this.timeout is not a function

      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:50:6)

  ● components/Image › prop "onLoad"

    TypeError: this.timeout is not a function

      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:59:6)

  ● components/Image › prop "onLoadEnd"

    TypeError: this.timeout is not a function

      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:70:6)

  ● components/Image › prop "onLoadStart"

    TypeError: this.timeout is not a function

      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:81:6)

  ● components/Image › prop "source" › encountered a declaration exception

    TypeError: this.timeout is not a function

      at Suite.<anonymous> (src/components/Image/__tests__/index-test.js:119:6)
      at Suite.<anonymous> (src/components/Image/__tests__/index-test.js:118:1)
      at Object.<anonymous> (src/components/Image/__tests__/index-test.js:8:1)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at handleMessage (internal/child_process.js:695:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

 FAIL  src/components/TextInput/__tests__/index-test.js
  ● components/TextInput › prop "maxLength"

    expect(received).toEqual(expected)

    Expected value to equal:
      "10"
    Received:
      10

    Difference:

    Comparing two different types of values:
      Expected: string
      Received: number

      at Object.<anonymous> (src/components/TextInput/__tests__/index-test.js:92:33)

 FAIL  src/modules/createDOMElement/__tests__/index-test.js
  ● modules/createDOMElement › prop "testID"

    expect(received).toEqual(expected)

    Expected value to equal:
      null
    Received:
      undefined

    Difference:

    Comparing two different types of values:
      Expected: null
      Received: undefined

      at Object.<anonymous> (src/modules/createDOMElement/__tests__/index-test.js:53:37)

 FAIL  src/apis/AppRegistry/__tests__/index-test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/jest-cli/build/TestRunner.js:189:18)
      at process._tickCallback (node.js:369:9)

 FAIL  src/apis/AsyncStorage/__tests__/index-test.js (5.124s)
  ● apis/AsyncStorage › mergeLocalStorageItem › should have same behavior as react-native

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:477:19)
      at Timer.listOnTimeout (timers.js:92:15)


Test Suites: 6 failed, 9 skipped, 17 passed, 23 of 32 total
Tests:       11 failed, 13 skipped, 96 passed, 120 total
Snapshots:   0 total
Time:        8.023s
Ran all test suites.

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/opt/nvm/versions/node/v4.4.2/bin/node" "/usr/local/opt/nvm/versions/node/v4.4.2/bin/npm" "run" "test"
npm ERR! node v4.4.2
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! react-native-web@0.0.47 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-web@0.0.47 test script 'jest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/paularms/dev/react-native-web/npm-debug.log
```

Signed-off-by: Paul Armstrong <paul@spaceyak.com>

### CODE REVIEW

**Comment by necolas** [comment]
I've got all the tests passing in this branch: https://github.com/necolas/react-native-web/tree/gh-pr/249. Commented out the `Image` tests but could probably mock `window.Image`. What's the correct way to mock `localStorage` and `Image` with jest?

```
> jest

 PASS  src/components/Image/__tests__/index-test.js (5.252s)
 PASS  src/components/View/__tests__/index-test.js (5.292s)
  ● Console

    console.error node_modules/fbjs/lib/warning.js:36
      Warning: There is an internal error in the React performance measurement code. Did not expect ctor timer to start while componentDidMount timer is still in progress for another instance.

 PASS  src/components/Text/__tests__/index-test.js
  ● Console

    console.error node_modules/fbjs/lib/warning.js:36
      Warning: There is an internal error in the React performance measurement code. Did not expect ctor timer to start while componentDidMount timer is still in progress for another instance.

 PASS  src/components/ProgressBar/__tests__/index-test.js
 PASS  src/modules/createDOMElement/__tests__/index-test.js
 PASS  src/components/TextInput/__tests__/index-test.js (6.337s)
 PASS  src/components/Switch/__tests__/index-test.js
 PASS  src/apis/AppRegistry/__tests__/renderApplication-test.js
 PASS  src/apis/StyleSheet/__tests__/index-test.js
 PASS  src/apis/AsyncStorage/__tests__/index-test.js
 PASS  src/apis/StyleSheet/__tests__/i18nStyle-test.js
 PASS  src/apis/AppState/__tests__/index-test.js
 PASS  src/apis/UIManager/__tests__/index-test.js
 PASS  src/apis/I18nManager/__tests__/index-test.js
 PASS  src/modules/multiplyStyleLengthValue/__tests__/index-test.js
 PASS  src/apis/StyleSheet/__tests__/processVendorPrefixes-test.js
 PASS  src/apis/StyleSheet/__tests__/normalizeValue-test.js
 PASS  src/apis/StyleSheet/__tests__/expandStyle-test.js
 PASS  src/modules/flattenStyle/__tests__/index-test.js
 PASS  src/apis/StyleSheet/__tests__/processTransform-test.js
 PASS  src/apis/StyleSheet/__tests__/createReactStyleObject-test.js
 PASS  src/apis/StyleSheet/__tests__/processTextShadow-test.js
 PASS  src/apis/NetInfo/__tests__/index-test.js

Test Suites: 8 skipped, 23 passed, 23 of 31 total
Tests:       22 skipped, 103 passed, 125 total
Snapshots:   0 total
Time:        9.542s
Ran all test suites.
```

**Comment by paularmstrong** [comment]
If js-dom allows mocking `window.localStorage` or `window.Image`, it should be marked as a bug. You're normally not able to override most global apis (it doesn't throw an error, it'll just keep using the built-in). You'll probably have to rewrite things to use dependency-injection.

**Comment by necolas** [comment]
Updated the branch to use snapshots too. Removed problematic async tests; we'll have to rely on visual confirmation in the examples for features like clearing text on focus or image loading.

**Comment by necolas** [comment]
Closing but will merge https://github.com/necolas/react-native-web/pull/251

**Pull request closed without merging**
