### PR TITLE
Support for JSS

### PR DESCRIPTION
**Pull request by jtag05**
Incorporating JSS into this library is a personal must have for, if nothing else, cleanliness of generated code.

I've adapter the gist created by @faceyspacey in issue #245 into this pull request. The general idea of my solution was to not reinvent the wheel, but simply offer it as an alternative by using `babel-plugin-module-alias` to create a second `jss` version of the build.

### CODE REVIEW

**Comment by alloy** [comment]
@jtag05 Haven’t looked into this extensively, but just wanted to note that your patch does not work with RNW since [this change](https://github.com/necolas/react-native-web/commit/e5d8b58b53e361e4fe7a15a3137850c7936d8a9a) (e.g. missing `css.js` module).

**Comment by jtag05** [comment]
@alloy Thanks, I'm aware. The CSS performance update created some serious refactor needs on my end. I've had enough time to get it partially working locally, but haven't pushed the changes.

**Comment by jtag05** [comment]
@alloy If you'd like to take a stab at the issues I'm running in to, I'll push up what I have for you to see. Currently the initial classes aren't being assigned.

**Comment by jtag05** [comment]
I'm closing this pull request due to a major divergence in the way the StyleSheet api is incorporated from the time it was submitted. I've opened a new more concise request here #343

**Pull request closed without merging**
