### PR TITLE
Always hydrate

### PR DESCRIPTION
**Pull request by codejamninja**

### CODE REVIEW

**Comment by codejamninja** [comment]
Fixes #918 
Also refer to #733

**Comment by necolas** [comment]
I would like clear explanations for PRs. IIRC, hydrate will throw a warning in development if there's no SSR content to hydrate, which is why things are done this way.

**Comment by bevacqua** [comment]
@necolas could `AppRegistry.runApplication` at least take a flag that indicate we always want to hydrate, e.g `ssr: true`?

> `react-dom.development.js:5585` Warning: render(): Calling ReactDOM.render() to hydrate server-rendered markup will stop working in React v17. Replace the ReactDOM.render() call with ReactDOM.hydrate() if you want React to attach to the server HTML.

**Comment by bevacqua** [comment]
Also when you SSR, you get a console statement like `Running application "App" with appParams: …` which can be _huuuge_. Feels like this statement belongs on dev mode only

**Comment by necolas** [comment]
> could AppRegistry.runApplication at least take a flag to indicate we always want to hydrate, e.g ssr: true

Why?

> Feels like this statement belongs on dev mode only

React Native always prints it. It's not related to SSR either as it's part of the client-side code. I think it's probably ok to make it dev only for web though

**Comment by MrLoh** [comment]
@necolas React now throws the following Warning: `render(): Calling ReactDOM.render() to hydrate server-rendered markup will stop working in React v17. Replace the ReactDOM.render() call with ReactDOM.hydrate() if you want React to attach to the server HTML.`

So maybe adding a flag would be the best option after all?

**Comment by codejamninja** [comment]
I've just been temporarily ignoring it with the `ignore-warnings` module.

https://www.npmjs.com/package/ignore-warnings

**Pull request closed without merging**
