### PR TITLE
Add `onKeyPress` support for arrow keys

### PR DESCRIPTION
**Pull request by alexandergunnarson**
Resolves https://github.com/necolas/react-native-web/issues/791.

### CODE REVIEW

**Comment by necolas** [comment]
How does this resolve that issue?

This PR would also need tests and documentation updates. The commits would be flattened to please

**Comment by alexandergunnarson** [comment]
Yes, the commits can be flattened, though wouldn't that happen in a Squash and Merge? Let me know if you want them flattened prior to a potential merge.

As for tests and documentation updates, that's fine — I'll add those in. I was waiting on adding a bunch of additional metadata to this PR until we discussed #791. This PR implements Solution 2 of #791 but perhaps you'd want a different one because of reasons mentioned there. Could you take a look at it and we can discuss there?

**Comment by necolas** [comment]
I'd like them flattened please. I don't use the GitHub UI to manage PRs

**Comment by alexandergunnarson** [comment]
Okay, no problem! Will do

**Pull request closed without merging**
