### PR TITLE
[fix] ignore native-only TextInput props

### PR DESCRIPTION
**Pull request by rickiesmooth**
Hi this is my first PR. I've looked at a similar [PR](https://github.com/necolas/react-native-web/pull/753) and I hope everything is alright.
Ref #735

### CODE REVIEW

**Comment by necolas** [comment]
Is hitslop meant to work with text input?

**Comment by rickiesmooth** [comment]
I'm not sure but it was passed down to the dom and I thought this would prevent that.

**Comment by rickiesmooth** [comment]
It's getting hitslop from `...ViewPropTypes` but I couldn't find any reference to it in the text input.

**Comment by necolas** [comment]
I checked and `hitSlop` didn't do anything for `TextInput` in React Native

**Comment by necolas** [comment]
Thanks for this

**Comment by rickiesmooth** [comment]
Thanks for checking and for RNW!

**Pull request closed without merging**
