### PR TITLE
Add support for ScrollView pagingEnabled property

### PR DESCRIPTION
**Pull request by kristerkari**
Add support for ScrollView's pagingEnabled property using [CSS scroll snap](https://www.w3.org/TR/css-scroll-snap-1/)

Related issue #1057

Links:
- caniuse: https://caniuse.com/#feat=css-snappoints
- spec: https://www.w3.org/TR/css-scroll-snap-1/

### CODE REVIEW

**Comment by necolas** [comment]
Cloning the children won't work properly for the same reasons it didn't for sticky headers. We should combine those two into a single function that adds the wrapping view, if possible

**Comment by kristerkari** [comment]
> Cloning the children won't work properly for the same reasons it didn't for sticky headers

What was the issue? 

If I add a wrapping view, which styles should it have when `pagingEnabled` is `true`, so that it does not breaking the styles from each children?

**Comment by necolas** [comment]
The RN list views do not all forward style to the children. So the element you're cloning may ignore the style prop. Look at the sticky headers function you touched. The paging stuff can probably go in there

**Comment by kristerkari** [comment]
ok, I made changes to use the same map function for both `stickyHeaderIndices` and  `pagingEnabled`. I hope that I did not mess up the logic.

**Comment by necolas** [comment]
Nice work! Thank you for doing this

**Pull request closed without merging**
