### PR TITLE
fix: make correct documentation site link

### PR DESCRIPTION
**Pull request by tranhiepqna**

### CODE REVIEW

**Comment by necolas** [comment]
The link is correct

**Comment by gonzalch** [comment]
@necolas I don't think the link is correct, if I navigate to https://necolas.github.com/react-native-web/ I get this 404 error page -
image

I think changing this to https://necolas.github.io/react-native-web/docs/ would be more useful.

Found this PR and made this comment only because I was about to open a similar one.

**Comment by necolas** [comment]
Oh my bad, I read the PR backwards

**Comment by necolas** [comment]
Fixed now. Thanks

**Pull request closed without merging**
