### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by friederbluemle**
Just some minor automated formatting cleanups. Done by running `yarn fmt` (which runs prettier).

### CODE REVIEW

**Comment by friederbluemle** [comment]
@necolas - Are you currently accepting PRs for this repo? If yes, please advise which branch to use (I see some activity on the `next` branch, vs the default `master` branch...). Thanks!

**Comment by necolas** [comment]
Yes I am, thanks! But this one won't be merged as I had to fix it in the other branch anyway :)

**Comment by friederbluemle** [comment]
I understand. My question is about the "active" branch in this repo (the one that PRs should be submitted against)? It is not the default branch (`master`)?

**Comment by necolas** [comment]
it's master

**Comment by friederbluemle** [comment]
Okay thanks for the reply again @necolas - Is there a plan to fast forward master to next? If so, when?

**Comment by necolas** [comment]
I don't know when

**Comment by friederbluemle** [comment]
Okay, hopefully soon. ;) Since you're already using *tags* in this repo for releases (👍), there should be no need to keep *two* "main" branches for *one* codebase in *one* repo.

**Pull request closed without merging**
