### PR TITLE
Adding click handlers for react-native-web

### PR DESCRIPTION
**Pull request by icarus-sullivan**
**Versions**

```json
"react": "^15.5.4",
"react-dom": "^15.5.4",
"react-native-web": "0.0.116"
```

**This patch solves the following problem**

onPress events were not being triggered when pulling the latest library.

**Test plan**

**This pull request**

 

- [ ] includes documentation
- [ ] includes tests
- [ ]  includes benchmark reports
- [ ] includes an interactive example
- [ ] includes screenshots/videos

No tests should be necessary as this does not modify rendering or any other events.

### CODE REVIEW

**Comment by icarus-sullivan** [comment]
I do not believe this is related to the hidden internals of React + React-Dom

**Comment by necolas** [comment]
How am I supposed to reproduce the issue? In what environment

**Comment by icarus-sullivan** [comment]
Sorry, accidentally hit close instead of comment. Will build a react playground and link it. 

[Codepen mimics my environment](https://codepen.io/anon/pen/ayvgQy)

**Comment by icarus-sullivan** [comment]
@necolas Sorry to waste your time, my webpack-dev-server was breaking -_- 

Apologies, and keep up the great work.

**Comment by necolas** [comment]
No worries. Thanks for looking into it

**Pull request closed without merging**
