### PR TITLE
Add Alert API

### PR DESCRIPTION
**Pull request by JulianMayorga**
alert

# Motivation

React router 4 on a React Native Web app fails because [it needs `Alert` to work](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-native/NativeRouter.js#L4).

@necolas please let me know if there's anything you'd like me to improve.

Thanks to @vaukalak for making #305, which really helped me.

### CODE REVIEW

**Comment by necolas** [comment]
i don't think you're meant to be using the native router in a web app

**Comment by necolas** [comment]
I'm not going to merge this patch as it is not authored in the way I believe the Alert API needs to be implemented (e.g., using Portals). There's also another PR for this that is closer to what I would like to see. Thanks

**Comment by JulianMayorga** [comment]
@necolas you're right that the native router is not meant to be used in a web app. I do think it would make it easier for beginners to copy-paste the examples in react router native docs (like [this one](https://reacttraining.com/react-router/native/example/Basic)) into react native web apps.

**Comment by JulianMayorga** [comment]
I understand. I agree that portals would be a better way to implement Alert. Thanks for such a great framework! I appreciate all the work put into it.

**Pull request closed without merging**
