### PR TITLE
Initial SectionList support, works with the Expo tabs template

### PR DESCRIPTION
**Pull request by raarts**
Addresses #830 .

I'd really like some input on this. since some issues are remaining:

* I get a few of `Warning: React does not recognize the 'xxxxx' prop on a DOM element.`, and I could use some pointers on how to fix this. My guess is it has to do with setNativeProps()
* There's no doc yet, but why not point to the ReactNative page?
* Although this PR now works with the Expo tabs template, I'm deeply worried that it's fundamentally broken, since I [removed a call](https://github.com/necolas/react-native-web/pull/831/files#diff-5d3b6006279b241304e519d4460980fbR369) to ReactNative() which points to a huge body of code which even seems to tie into the bus between JS and Native code. I spent some time already implementing this PR, and I don't want to spend more only to be told it's going to be a huge undertaking.
* I haven't use flow, and CI marks a lot of tests are failing, but before I embark on fixing everything, I'd really like some feedback.

### CODE REVIEW

**Comment by necolas** [comment]
Hi this patch is currently too big and makes too many changes for me to effectively review

**Comment by raarts** [comment]
Alright. So it needs to be split up. The best route for that I guess would be to build on #659, I reached out to @rmevans9 and he said he's in no hurry to do anything with it, so I am willing to assume maintenance of that part if that helps. Please advise.
This issue is a blocker in my startup so I am motivated to make this work.

**Comment by necolas** [comment]
You can unblock yourself by using webpack to alias the import path to your local hack, or use a fork

**Comment by raarts** [comment]
Sure I'm doing that but I don't like temporary solutions. Any input on the rest of my comment?

**Comment by necolas** [comment]
I've been working my way through underlying functionality that's needed to get the lists working without significant modifications. None of the past list PRs have worked or been debugged by the author, which is why they weren't merged.

**Pull request closed without merging**
