### PR TITLE
Added LocationApi

### PR DESCRIPTION
**Pull request by adnan1naeem**
Added Location Api feature

### CODE REVIEW

**Comment by necolas** [comment]
Hi. I don't know what this API. PRs should explain to the maintainer what their purpose is. This kind of looks like something taken from ReactXP and most of the patch is type interfaces and unwanted changes to package.json files etc. It's not something I will merge in this form

**Comment by adnan1naeem** [comment]
Hi,
I want something like  location api in react_native_web.can u please
provide me that functionality for getting current location

**Comment by necolas** [comment]
React Native implements the same geolocation API as the web https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition

**Comment by adnan1naeem** [comment]
I want Location Api support for mobile + web (both platforms)

**Comment by MoOx** [comment]
Necolas just said that the RN api is ripped from the browser API. So you are not really supposed to need something more for the web, that what the browser already gives you.
If you have more detailed arguments, please share those by sharing the motivations.

**Pull request closed without merging**
