### PR TITLE
Fixed bug with animations and i18n

### PR DESCRIPTION
**Pull request by lyahdav**
Styles were not correctly getting flipped in `setNativeProps`.

### CODE REVIEW

**Comment by necolas** [comment]
Thanks, please can you share a test case that exposes the problem?

**Comment by lyahdav** [comment]
Sorry I didn't get a chance to write a test, haven't had time recently. Thanks for merging!

**Comment by necolas** [comment]
Are you using react-native-web at Uber?

**Comment by lyahdav** [comment]
Yes, I showed you a screen where we use it when I saw you at React Wednesdays at Airbnb a while back.

**Pull request closed without merging**
