### PR TITLE
Fix grey circle animation

### PR DESCRIPTION
**Pull request by mamaz**
**This patch solves the following problem**
Current implementation: the grey circle / shadow box does not automatically disappear during movement from `active` to inactive, vice versa. 

This pull request fix this issue by using `mouseUp`, `mouseDown`, `touchStart`, and `touchEnd` event instead of `focus`/ `blur`.

**Updates**:
Now it only uses `mouseUp` to fire the grey circle, and `onChange` to dismiss it.

**Test plan**
run `yarn examples` find the Switch on `component: Switch`, tap and hold the switch.

**This pull request**

- [ ] includes documentation
- [ ] includes tests
- [ ] includes benchmark reports
- [x] includes an interactive example
- [x] includes screenshots/videos

Examples:

switch

### CODE REVIEW

**Comment by necolas** [comment]
That's because the control is still focused. Why is this a problem for you?

**Comment by mamaz** [comment]
@necolas 
because the grey circle does not automatically disappear, it needs to be unfocused by tapping somewhere on the browser, 
I hope I can make it like the switch from React Native Material Kit `https://github.com/xinthink/react-native-material-kit`

**Comment by mamaz** [comment]
@necolas 
I have finished this, could you have a look and give feedback for this. Thank you.

**Comment by necolas** [comment]
Thanks. I don't think this approach will work for mouse + touch + keyboard without getting pretty messy. Probably best to rely on the `modality` functionality and convert that into a focus manager of sorts, so components like `Switch` can determine whether a keyboard is in use and requires the focus state. I'll look into that at some point.

**Pull request closed without merging**
