### PR TITLE
Add support for Carbon UI

### PR DESCRIPTION
**Pull request by tuckerconnelly**
This is for compatibility with Carbon UI. `onLayout` worked great :)

- Switches from `Stylesheet.create()` to using classname
- Normalized `onScroll` event (added nativeEvent)
- Adds Linking

**Test Plan**

Biggest change was moving from `Stylesheet.create()` to classname. Reviewed the jest snapshot differences and updated them.

### CODE REVIEW

**Comment by necolas** [comment]
Please can you remove the style changes

**Comment by tuckerconnelly** [comment]
Why?

**Comment by necolas** [comment]
Your PR does 3 different, unrelated things. I'd rather review and merge single-purpose PRs with explanations. I'm currently iterating on the ways styles are handled in the library and I don't know what your changes are for

**Comment by tuckerconnelly** [comment]
Sure np, will tomorrow.

**Comment by necolas** [comment]
I added Linking support in dc54e03625ae0e202ba9594da93a820149f82985

**Comment by necolas** [comment]
And ScrollView event normalization in 4c46126ffe83ecbd91eb4779de5175c1fabda82d (was needed for the ListView branch too)

**Comment by tuckerconnelly** [comment]
Thanks necolas. Broke what was remaining into https://github.com/necolas/react-native-web/pull/283 and https://github.com/necolas/react-native-web/pull/284

**Pull request closed without merging**
