### PR TITLE
Port over VirtualizedList from react-native (Updated to master)

### PR DESCRIPTION
**Pull request by rmevans9**
**This patch solves the following problem**

This is #474 just updated to master for easy merging. I also updated the story to match the new storybook setup.

**Test Plan**
Run it in storybook and ensure it works correctly

**This pull request**

- [ ] includes documentation
- [ ] includes tests
- [ ] includes benchmark reports
- [x] includes an interactive example
- [ ] includes screenshots/videos

### CODE REVIEW

**Comment by jbovenschen** [comment]
Thanks for picking this up again, would really like it when we could use this in a web application, is there anything I can do to get it done?

**Comment by teabyii** [comment]
Is there any progress about this PR now? VirtualizedList is an important component for my project, so what can I help?

**Comment by davidkwan95** [comment]
Hey, is this PR getting any merge soon? I need it in my project in the near future. I'll have to implement it myself if it doesn't get any merge soon.

**Comment by zth** [comment]
I'm also very interested in this, we make heavy use of virtualized lists in various flavours in our apps. Anything we can do to help?

**Comment by noeljackson** [comment]
@rmevans9 do you have contact details? Have message for you.

**Comment by rardoz** [comment]
I wannnnt

**Comment by yokomizor** [comment]
Let me know if you need help with docs, tests and benchmark.

**Pull request closed without merging**
