### PR TITLE
Fix keyboard number type

### PR DESCRIPTION
**Pull request by petrbela**
Numeric/decimal keyboardType should also set type=number to allow only numeric keys on desktop and mobile.

### CODE REVIEW

**Comment by petrbela** [comment]
Related to numeric input, could RNW also support `min`, `max` and `step`? I know they don't exist in RN but they'd simply be ignore there. I can add it to this PR or create a separate one.

**Comment by necolas** [comment]
See https://github.com/necolas/react-native-web/pull/1709

**Comment by petrbela** [comment]
@necolas Fair enough. Would you be okay with adding web-only `type`, `min`, `max`, and `step` props to enable explicitly enforcing specific browser behavior when the developer chooses to do so?

**Comment by necolas** [comment]
I don't think so, as that would puncture the API and allow completely different results to be produced on web.

You can either implement that functionality cross platform in JS, or use the `unstable_createElement` API to create a custom web element using those props, and decide where to fork/recombine that with your RN code in your product.

**Comment by necolas** [comment]
But this is a relevant issue for future xplat react APIs, as it surfaces more limitations of RN's `TextInput` API

**Pull request closed without merging**
