### PR TITLE
[fix] Import react-art only client side to avoid crash

### PR DESCRIPTION
**Pull request by anonkey**
Little fix to avoid crash on server side rendering

### CODE REVIEW

**Comment by necolas** [comment]
This isn't a reliable approach. There's a fix upstream that I'm hoping will make it into the 16.3 react releases

**Comment by koulmomo** [comment]
@anonkey you can avoid the crash by using https://www.npmjs.com/package/babel-plugin-react-native-web along with making sure you never import all of React Native and only using named imports instead.

```js
// never do this
import ReactNative from 'react-native';

// do this instead
import {View, Text} from 'react-native';
```

The downside is that you will have to run transpiled code on the server.

**Comment by necolas** [comment]
I don't know when the next react release will fix this. So actually I'll reopen this and consider a temporary fix. May also make 'react-art' a peer dependency like the other react packages

**Comment by anonkey** [comment]
@koulmomo Thanks a lot.
@necolas  Yes i didn't think about it, it seem a good idea.

**Comment by necolas** [comment]
Art has been updated and this issue should be fixed

**Pull request closed without merging**
